apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-diff-logger-config
  labels:
    app: kubernetes-diff-logger
data:
  config.yml: |-
    differs:
    - nameFilter: "*"
      type: "deployment"
    - nameFilter: "*"
      type: "statefulset"
    - nameFilter: "*"
      type: "daemonset"
